# Generated by Django 5.0.6 on 2024-07-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_genero_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Descripcion')),
                ('url', models.URLField(max_length=70)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Desarrollador',
                'verbose_name_plural': 'Desarrolladores',
            },
        ),
        migrations.CreateModel(
            name='Distibuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Distibuidor',
                'verbose_name_plural': 'Distibuidores',
            },
        ),
        migrations.CreateModel(
            name='EdadRecomendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2, unique=True, verbose_name='Número')),
                ('color', models.CharField(max_length=8, unique=True, verbose_name='Color')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Modo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_juego', models.CharField(max_length=10, unique=True, verbose_name='Modo de juego')),
            ],
            options={
                'verbose_name': 'Modo de Juego',
                'verbose_name_plural': 'Modos de Juego',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Plataforma')),
                ('retrocompatible', models.BooleanField(default=False, verbose_name='Retrocompatible')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Tipo de Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Descripcion')),
                ('sinopsis', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Sinopsis')),
                ('anio', models.CharField(blank=True, max_length=4, null=True, verbose_name='Año de publicación')),
                ('img', models.CharField(blank=True, max_length=40, null=True, verbose_name='Imagen')),
                ('precio', models.CharField(blank=True, max_length=6, null=True, verbose_name='Precio')),
                ('tenemos', models.CharField(blank=True, choices=[('j', 'Juego'), ('n', 'No tenemos'), ('r', 'Recopilación')], default='j', max_length=1, null=True, verbose_name='Tenemos')),
                ('wish_list', models.BooleanField(default=False, verbose_name='Wish List')),
                ('formato', models.CharField(choices=[('p', 'Pirata'), ('d', 'Digital'), ('c', 'Código de descarga'), ('f', 'Físico')], default='f', max_length=20, verbose_name='Formato')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesapp.coleccion', verbose_name='Colección')),
                ('desarrollador', models.ManyToManyField(related_name='videojuegos_desarrolladores', to='gamesapp.desarrollador', verbose_name='Desarrollador')),
                ('distribuidor', models.ManyToManyField(related_name='videojuegos_distribuidores', to='gamesapp.distibuidor', verbose_name='Distribuidor')),
                ('edad_recomendada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesapp.edadrecomendada', verbose_name='Edad Recomendada')),
                ('genero', models.ManyToManyField(related_name='videojuegos_generos', to='common.genero', verbose_name='Género')),
                ('modo_juego', models.ManyToManyField(related_name='videojuegos_modos_juego', to='gamesapp.modo', verbose_name='Modo de Juego')),
                ('plataforma', models.ManyToManyField(related_name='videojuegos_plataformas', to='gamesapp.plataforma', verbose_name='Plataforma')),
                ('programa', models.ManyToManyField(related_name='videojuegos_programa', to='gamesapp.tipocontenido', verbose_name='Programa')),
                ('tipo_contenido', models.ManyToManyField(related_name='videojuegos_tipo_contenido', to='gamesapp.tipocontenido', verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
            },
        ),
        migrations.CreateModel(
            name='Recopilacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Descripcion')),
                ('videojuegos', models.ManyToManyField(related_name='recopilaciones', to='gamesapp.videojuego', verbose_name='Videojuegos')),
            ],
            options={
                'verbose_name': 'Recopilación',
                'verbose_name_plural': 'Recopilaciones',
            },
        ),
    ]
