# Generated by Django 5.0.6 on 2024-07-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_genero_options'),
        ('gamesapp', '0002_alter_videojuego_formato_alter_videojuego_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='carpeta',
            field=models.ManyToManyField(related_name='videojuegos_carpetas', to='common.carpeta', verbose_name='Carpeta'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='formato',
            field=models.CharField(choices=[('c', 'Código de descarga'), ('d', 'Digital'), ('p', 'Pirata'), ('f', 'Físico')], default='f', max_length=20, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tenemos',
            field=models.CharField(blank=True, choices=[('j', 'Juego'), ('n', 'No tenemos'), ('r', 'Recopilación')], default='j', max_length=1, null=True, verbose_name='Tenemos'),
        ),
    ]
