# Generated by Django 5.0.6 on 2024-07-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_genero_options'),
        ('gamesapp', '0003_videojuego_carpeta_alter_videojuego_formato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='anio',
            field=models.CharField(max_length=4, verbose_name='Año de publicación'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='carpeta',
            field=models.ManyToManyField(blank=True, related_name='videojuegos_carpetas', to='common.carpeta', verbose_name='Carpeta'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesapp.coleccion', verbose_name='Colección'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='formato',
            field=models.CharField(blank=True, choices=[('p', 'Pirata'), ('c', 'Código de descarga'), ('f', 'Físico'), ('d', 'Digital')], default='f', max_length=20, null=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='programa',
            field=models.ManyToManyField(blank=True, related_name='videojuegos_programa', to='gamesapp.tipocontenido', verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tenemos',
            field=models.CharField(blank=True, choices=[('r', 'Recopilación'), ('j', 'Juego'), ('n', 'No tenemos')], default='j', max_length=1, null=True, verbose_name='Tenemos'),
        ),
    ]
