# Generated by Django 5.0.6 on 2024-07-10 18:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0005_alter_videojuego_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edadrecomendada',
            name='color',
            field=models.CharField(max_length=8, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='descripcion',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='formato',
            field=models.CharField(blank=True, choices=[('d', 'Digital'), ('p', 'Pirata'), ('f', 'Físico'), ('c', 'Código de descarga')], default='f', max_length=20, null=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='sinopsis',
            field=ckeditor.fields.RichTextField(blank=True, max_length=4000, null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tenemos',
            field=models.CharField(blank=True, choices=[('n', 'No tenemos'), ('r', 'Recopilación'), ('j', 'Juego')], default='j', max_length=1, null=True, verbose_name='Tenemos'),
        ),
    ]
