# Generated by Django 5.0.6 on 2024-07-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0006_alter_edadrecomendada_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='formato',
            field=models.CharField(blank=True, choices=[('d', 'Digital'), ('c', 'Código de descarga'), ('p', 'Pirata'), ('f', 'Físico')], default='f', max_length=20, null=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tenemos',
            field=models.CharField(blank=True, choices=[('n', 'No tenemos'), ('j', 'Juego'), ('r', 'Recopilación')], default='j', max_length=1, null=True, verbose_name='Tenemos'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tipo_contenido',
            field=models.ManyToManyField(blank=True, related_name='videojuegos_tipo_contenido', to='gamesapp.tipocontenido', verbose_name='Tipo de Contenido'),
        ),
    ]
