# Generated by Django 5.0.6 on 2024-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0007_alter_videojuego_formato_alter_videojuego_tenemos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='formato',
            field=models.CharField(blank=True, choices=[('p', 'Pirata'), ('d', 'Digital'), ('c', 'Código de descarga'), ('f', 'Físico')], default='f', max_length=20, null=True, verbose_name='Formato'),
        ),
    ]
