# Generated by Django 5.0.6 on 2024-07-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_genero_options'),
        ('gamesapp', '0009_auto_20240713_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edadrecomendada',
            options={'verbose_name': 'Edad Recomendada', 'verbose_name_plural': 'Edades Recomendadas'},
        ),
        migrations.AlterModelOptions(
            name='tipocontenido',
            options={'verbose_name': 'Tipo de contenido', 'verbose_name_plural': 'Tipos de contenido'},
        ),
        migrations.AddField(
            model_name='recopilacion',
            name='anio',
            field=models.CharField(max_length=4, null=True, verbose_name='Año de publicación'),
        ),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='carpeta',
        #    field=models.ManyToManyField(blank=True, related_name='recopilaciones_carpetas', to='common.carpeta', verbose_name='Carpeta'),
        #),
        migrations.AddField(
            model_name='recopilacion',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesapp.coleccion', verbose_name='Colección'),
        ),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='desarrollador',
        #    field=models.ManyToManyField(related_name='recopilaciones_desarrolladores', to='gamesapp.desarrollador', verbose_name='Desarrollador'),
        #),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='distribuidor',
        #    field=models.ManyToManyField(related_name='recopilaciones_distribuidores', to='gamesapp.distibuidor', verbose_name='Distribuidor'),
        #),
        migrations.AddField(
            model_name='recopilacion',
            name='edad_recomendada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesapp.edadrecomendada', verbose_name='Edad Recomendada'),
        ),
        migrations.AddField(
            model_name='recopilacion',
            name='formato',
            field=models.CharField(blank=True, choices=[('f', 'Físico'), ('d', 'Digital'), ('c', 'Código de descarga'), ('p', 'Pirata')], default='f', max_length=20, null=True, verbose_name='Formato'),
        ),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='genero',
        #    field=models.ManyToManyField(related_name='recopilaciones_generos', to='common.genero', verbose_name='Género'),
        #),
        migrations.AddField(
            model_name='recopilacion',
            name='img',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Imagen'),
        ),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='modo_juego',
        #    field=models.ManyToManyField(related_name='recopilaciones_modos_juego', to='gamesapp.modo', verbose_name='Modo de Juego'),
        #),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='plataforma',
        #    field=models.ManyToManyField(related_name='recopilaciones_plataformas', to='gamesapp.plataforma', verbose_name='Plataforma'),
        #),
        migrations.AddField(
            model_name='recopilacion',
            name='precio',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Precio'),
        ),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='programa',
        #    field=models.ManyToManyField(blank=True, related_name='recopilaciones_programa', to='gamesapp.tipocontenido', verbose_name='Programa'),
        #),
        migrations.AddField(
            model_name='recopilacion',
            name='sinopsis',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Sinopsis'),
        ),
        migrations.AddField(
            model_name='recopilacion',
            name='tenemos',
            field=models.CharField(blank=True, choices=[('n', 'No tenemos'), ('j', 'Juego'), ('r', 'Recopilación')], default='j', max_length=1, null=True, verbose_name='Tenemos'),
        ),
        #migrations.AddField(
        #    model_name='recopilacion',
        #    name='tipo_contenido',
        #    field=models.ManyToManyField(blank=True, related_name='recopilaciones_tipo_contenido', to='gamesapp.tipocontenido', verbose_name='Tipo de Contenido'),
        #),
        migrations.AddField(
            model_name='recopilacion',
            name='wish_list',
            field=models.BooleanField(default=False, verbose_name='Wish List'),
        ),
        migrations.AlterField(
            model_name='modo',
            name='modo_juego',
            field=models.CharField(max_length=25, unique=True, verbose_name='Modo de juego'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='formato',
            field=models.CharField(blank=True, choices=[('f', 'Físico'), ('d', 'Digital'), ('c', 'Código de descarga'), ('p', 'Pirata')], default='f', max_length=20, null=True, verbose_name='Formato'),
        ),
        migrations.AlterUniqueTogether(
            name='recopilacion',
            unique_together={('nombre', 'anio')},
        ),
    ]
