# Generated by Django 5.0.6 on 2024-07-10 17:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_genero_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('biografia', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Biografía')),
                ('url', models.URLField(max_length=70)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dirección')),
                ('url', models.URLField(max_length=70)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('portada', models.CharField(blank=True, max_length=40, null=True, verbose_name='Portada')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('fecha_leido', models.DateField(blank=True, null=True, verbose_name='Fecha de leído')),
                ('leido_por', models.CharField(blank=True, max_length=30, null=True, verbose_name='Leído por')),
                ('precio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Precio')),
                ('paginas', models.CharField(blank=True, max_length=4, null=True, verbose_name='Páginas')),
                ('tenemos', models.CharField(blank=True, choices=[('r', 'Recopilación'), ('n', 'No tenemos'), ('j', 'Juego')], default='j', max_length=1, null=True, verbose_name='Tenemos')),
                ('wish_list', models.BooleanField(default=False, verbose_name='Wish List')),
                ('autor', models.ManyToManyField(related_name='libro_autores', to='booksapp.autor', verbose_name='Autor')),
                ('carpeta', models.ManyToManyField(related_name='libros_carpeta', to='common.carpeta', verbose_name='Carpeta')),
                ('editorial', models.ManyToManyField(related_name='libro_editoriales', to='booksapp.editorial', verbose_name='Editorial')),
                ('genero', models.ManyToManyField(related_name='libro_generos', to='common.genero', verbose_name='Genero')),
                ('idioma', models.ManyToManyField(related_name='libro_idiomas', to='booksapp.idioma', verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
