# Generated by Django 5.0.6 on 2024-07-10 18:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, max_length=4000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tenemos',
            field=models.CharField(blank=True, choices=[('n', 'No tenemos'), ('r', 'Recopilación'), ('j', 'Juego')], default='j', max_length=1, null=True, verbose_name='Tenemos'),
        ),
    ]
